### ISSUE TITLE
If the execution is < 1ms then global > 100 %

### ISSUE THREAD

**Issue by maitrepylos** [hoaproject/Bench#29]
Sample : 
```php
use Hoa\Bench;
 
 
$tab = \SplFixedArray::fromArray(['Gg', 'est', 'le', 'plus', 'beau']);
 
$bench = new Bench();
 
$bench->one->start();
 
for($i=0;$i<$tab->count();$i++){
 
    echo $tab[$i];
 
}
 
$bench->one->stop();
 
 
$bench->two->start();
 
//le foreach
 
foreach($tab as $value){
 
    echo $value;
}
 
$bench->two->stop();
 
 
echo $bench;
```

Result : 

__global__  ||||||||||||||||||||||||||||||||||||||||||||||||||||||   0ms, 104.1%
     one         ||||||||||||||||||||||                                   0ms,  43.2%
     two         ||||||||||                                               0ms,  19.1%

**Comment by 1e1** [comment]
I suggest adding `pause()` and `resume()`. Then `getStatistic()` will call these methods to loop on paused Marks.

**Comment by Hywan** [comment]
@1e1 Agree.
