### ISSUE TITLE
Rename isRunning to isStarted in Bench.php

### ISSUE THREAD

**Issue by 1e1** [hoaproject/Bench#33]
Renamming property and method isRunning to isStarted should be more explicit. 
For a while `isRunning()` should be depricated. 

cf https://github.com/hoaproject/Bench/pull/30/files#r36389896

**Comment by Hywan** [comment]
This is more question like an issue, because it will break the BC and we would like to avoid that.

**Comment by Hywan** [comment]
I assigned @vonglasow to lead the reflection.

**Comment by vonglasow** [comment]
@1e1 so why you want to rename this api? What is the betterment to rename the method?

**Comment by vonglasow** [comment]
@1e1 do we continue the discussion or can we close this issue ?

**Comment by vonglasow** [comment]
After [discussion](http://discourse.hoa-project.net/t/issue-rename-isrunning-to-isstarted-in-bench-php/241), we have agreed to rename this method. @1e1 can you handle it and create a PR?
